<!DOCTYPE html>
<html>
<head>
    <title>Welcome</title>
    <link href="https://fonts.googleapis.com/css2?family=Philosopher&family=Pattaya&display=swap" rel="stylesheet">
    <style>
body {
background-color: #6096A6;
}

h1{
         color: #443B50;
     font-size: 50px;
     font-family: "Pattaya", sans-serif;
     }

         a{
          color:#8A678A;
          font-size: 20px;
          font-family: "Pattaya", sans-serif;
          padding:10px;
     text-decoration:none;
     text-align:center;
     display:block;
         }

</style>
<body>
<header align="center">
  <h1>Welcome!</h1>
</header>
<a href="/login">Enter</a>
</body>
</html>